server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/one_piece_api
    username: root
    password: todounamor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    whitelabel:
      enabled: 'false'

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/one_piece_api_test
    username: root
    password: todounamor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    whitelabel:
      enabled: 'false'